# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export EDITOR="nvim"
export PATH="$PATH:$HOME/.local/bin:./bin"

# Eza (https://eza.rocks/)
alias ls='eza -lh --group-directories-first --icons=auto'
alias lsa='ls -a'
alias lt='eza --tree --level=2 --long --icons --git'
alias lta='lt -a'

# Fuzzy finder (https://junegunn.github.io/fzf/, https://github.com/sharkdp/bat)
alias ff="fzf --preview 'bat --style=numbers --color=always {}'"

# Smart cd (https://github.com/ajeetdsouza/zoxide)
alias cd="zd"
zd() {
  if [[ $# -eq 0 ]]; then
    builtin cd ~ && return
  elif [[ -d $1 ]]; then
    builtin cd "$1"
  else
    z "$@" && printf "-> " && pwd || echo "Error: Directory not found"
  fi
}

# Directories
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# Tools
alias c='opencode'
alias cx='claude --permission-mode=plan --allow-dangerously-skip-permissions'
alias d='docker'
alias r='rails'
alias v='vim'
alias t='tmux attach || tmux new'
n() { if [[ $# -eq 0 ]]; then nvim .; else nvim "$@"; fi; }

# Git
alias g='git'
alias gcm='git commit -m'
alias gcam='git commit -a -m'
alias gcad='git commit -a --amend'

# Init
eval "$(mise activate bash)" # https://mise.jdx.dev/
eval "$(starship init bash)" # https://starship.rs/
eval "$(zoxide init bash)"   # https://github.com/ajeetdsouza/zoxide
